services:
  api:
    environment:
      - TZ=America/Sao_Paulo
  worker:
    environment:
      - TZ=America/Sao_Paulo
  db:
    environment:
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
